# Generated by Django 5.2.7 on 2025-11-02 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='systemconfig',
            old_name='form_time_type',
            new_name='form_item_type',
        ),
    ]
